
# Build node
FROM node:14.21-alpine as node
COPY /frontend /frontend
RUN cd frontend && npm install && npm run build
RUN rm -rf /frontend/node_modules

# Final image
FROM nginx:1.24.0-alpine3.17-slim

RUN rm /etc/nginx/conf.d/default.conf

COPY /etc/nginx/default.conf /etc/nginx/conf.d/

COPY --from=node /frontend /opt/app/frontend


# ENTRYPOINT ["/usr/local/bin/unit-docker-entrypoint.sh"]

# CMD ["unitd", "--no-daemon", "--control", "unix:/run/control.unit.sock"]